import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { NoteProvider } from '@/contexts/NoteProvider';
import { SettingProvider } from '@/contexts/SettingProvider';
import { ThemeProvider } from 'next-themes';
import AuthProvider from '@/contexts/AuthProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-slate-900 `}
      >
        <AuthProvider>
          <SettingProvider>
            <ThemeProvider
              attribute={'class'}
              enableSystem
              defaultTheme='system'
            >
              <NoteProvider>
                <main>{children}</main>
              </NoteProvider>
            </ThemeProvider>
          </SettingProvider>
        </AuthProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
